[package]
name = "datalog"
version = "0.1.1"
edition = "2021"
license = "MPL-2.0"
description = "Datalog Engine"

[dependencies]
nom = { workspace = true }
shared = { path = "../shared" }
rayon = { workspace = true }