[package]
name = "shared"
version = "0.1.1"
edition = "2021"
description = "Shared utilities and global state for the workspace"

[dependencies]
rayon = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }