[package]
name = "kolibrie-http-server"
version = "0.1.1"
edition = "2021"

[dependencies]
kolibrie = { path = "../kolibrie" }
datalog =  { path = "../datalog" }
shared = { path = "../shared" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"